"""Add OTP field to User model

Revision ID: 85693b31b1ed
Revises: a9e7c1f7bd29
Create Date: 2024-04-19 21:58:26.124657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85693b31b1ed'
down_revision = 'a9e7c1f7bd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
